### ISSUE TITLE
Versions compability

### ISSUE THREAD

**Issue by rafaltrojanowski** [j-mcnally/ember-cli-chrome#10]
Hi,

I get: Uncaught TypeError: template.buildRenderNodes is not a function

when I upgraded Ember to 1.13.5

Is it possible to use ember-cli-chrome with latest version?
Which template compiler should I choose?
Does it support HTMLbars?

Probably this problem isn't related to add-on directly, I'd like make sure.
Btw ember CLI Version 1.13.1 is available.

Cheers

**Comment by rafaltrojanowski** [comment]
It works with CLI 1.13.1 and HTMLBars as well. I had problem with old handlebars(1.3.0).
